// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWuoFj2qtX2P5ef7qWud4BEaQoC9EOzg',
    appId: '1:760131071256:web:b5d3c1ca0c2f243a6d426d',
    messagingSenderId: '760131071256',
    projectId: 'shorts-a5c63',
    authDomain: 'shorts-a5c63.firebaseapp.com',
    storageBucket: 'shorts-a5c63.appspot.com',
    measurementId: 'G-9E8013L5Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMa4ZzRdp7pn72L_2AUjnm1R1Nf0n5kk',
    appId: '1:760131071256:android:5624c83c75ae891c6d426d',
    messagingSenderId: '760131071256',
    projectId: 'shorts-a5c63',
    storageBucket: 'shorts-a5c63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZIqIx1S4LbiQYLlCjqLIK1kXbmU0-G8',
    appId: '1:760131071256:ios:ff01999b2ea346aa6d426d',
    messagingSenderId: '760131071256',
    projectId: 'shorts-a5c63',
    storageBucket: 'shorts-a5c63.appspot.com',
    iosClientId: '760131071256-g7lrtjh94bdjk6f5qd31mch9295m345d.apps.googleusercontent.com',
    iosBundleId: 'com.CodeHack.shorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZIqIx1S4LbiQYLlCjqLIK1kXbmU0-G8',
    appId: '1:760131071256:ios:eb825509ef2185956d426d',
    messagingSenderId: '760131071256',
    projectId: 'shorts-a5c63',
    storageBucket: 'shorts-a5c63.appspot.com',
    iosClientId: '760131071256-si0br0oht2c6bfjumdrjkhi5k2ki7dko.apps.googleusercontent.com',
    iosBundleId: 'com.CodeHack.shorts.RunnerTests',
  );
}
